title: "CSSans Pro - The flexbile CSS font"
url: "cssans.pro"
baseurl: ""
is_production: true
filesize: 16.5

permalink: /:title/
markdown: kramdown

exclude: ["node_modules",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "package.json",
          "package-lock.json",
          "README.md",
          "CNAME",
          "dist"]


