url: "cssans.pro"
baseurl: ""
is_production: true
title: "CSSans Pro"
subtitle: "The Colourful, Sassy, CSS Font"
documentation: "https://github.com/ZeroSpree/CSSans.Pro"
download: "https://cssans.pro/dist/cssans.min.css"
filesize: "16.9kb"

permalink: /:title/
markdown: kramdown

exclude: ["node_modules",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "package.json",
          "package-lock.json",
          "README.md",
          "CNAME"]


