title: "CSSans Pro - The flexbile CSS font"
url: "zerospree.github.io"
baseurl: "CSSans.Pro"
is_production: true
filesize: 9

permalink: /:title/
markdown: kramdown

exclude: ["node_modules",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "package.json",
          "package-lock.json",
          "README.md"]
