url: "https://cssans.pro"
baseurl: ""
is_production: true
title: "CSSans Pro"
subtitle: "The Colourful, Sassy, CSS Font"
documentation: "https://github.com/ZeroSpree/CSSans.Pro#readme"
download: "https://github.com/ZeroSpree/CSSans.Pro/blob/master/dist/cssans.min.css"
splash: "cssans.pro.jpg"
filesize: 27.5

permalink: /:title/
markdown: kramdown

exclude: ["node_modules",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "package.json",
          "package-lock.json",
          "README.md",
          "CNAME"]


